#!/bin/bash


##########################################
#### Set local variable  for scripts #####
##########################################

echocolor "Set local variable for scripts"
sleep 3

# Network model (provider or selfservice)
network_model=provider

#  Ipaddress variable and Hostname variable
## Assigning IP for controller node
CTL_EXT_IP=192.168.40.34
CTL_EXT_NETMASK=255.255.255.0
CTL_EXT_IF=eth0
CTL_MGNT_IP=192.168.50.39
CTL_MGNT_NETMASK=255.255.255.0
CTL_MGNT_IF=eth1

## Assigning IP for Compute1 host
COM1_EXT_IP=192.168.40.38
COM1_EXT_NETMASK=255.255.255.0
COM1_EXT_IF=eth0
COM1_MGNT_IP=192.168.50.24
COM1_MGNT_NETMASK=255.255.255.0
COM1_MGNT_IF=eth1

## Gateway for EXT network
GATEWAY_EXT_IP=192.168.40.1
CIDR_EXT=192.168.40.0/24
CIDR_MGNT=192.168.50.0/24

## Hostname variable
HOST_CTL=controller
HOST_COM1=compute1

VOLUME_NAME=vdb

# Password variable
DEFAULT_PASS="Vnpt123"

ADMIN_PASS=$DEFAULT_PASS
DEMO_PASS=$DEFAULT_PASS
DOMAIN_ADMIN_PASS=$DEFAULT_PASS
RABBIT_PASS=$DEFAULT_PASS
KEYSTONE_DBPASS=$DEFAULT_PASS	
GLANCE_DBPASS=$DEFAULT_PASS	
GLANCE_PASS=$DEFAULT_PASS	
METADATA_SECRET=$DEFAULT_PASS	
NEUTRON_DBPASS=$DEFAULT_PASS	
NEUTRON_PASS=$DEFAULT_PASS	
NOVA_PASS=$DEFAULT_PASS	
NOVA_DBPASS=$DEFAULT_PASS
PLACEMENT_PASS=$DEFAULT_PASS
PLACEMENT_DBPASS=$DEFAULT_PASS
CINDER_PASS=$DEFAULT_PASS
CINDER_DBPASS=$DEFAULT_PASS
BARBICAN_PASS=$DEFAULT_PASS
BARBICAN_DBPASS=$DEFAULT_PASS
HEAT_PASS=$DEFAULT_PASS
HEAT_DBPASS=$DEFAULT_PASS
HEAT_DOMAIN_PASS=$DEFAULT_PASS
MAGNUM_PASS=$DEFAULT_PASS
MAGNUM_DBPASS=$DEFAULT_PASS
OCTAVIA_PASS=$DEFAULT_PASS
OCTAVIA_DBPASS=$DEFAULT_PASS

PASS_SSL=$DEFAULT_PASS